### ISSUE TITLE
 阿里云登录失败

### ISSUE THREAD

**Issue by wuchenjuna** [xianrenjituan/BaiduYunToAliYun#1]
![XXO4FH`G`7K`%_4 PX56_)F](https://user-images.githubusercontent.com/125883415/220885806-ea9f5999-90c2-4125-9655-dba7b20b9d57.png)
想知道如何解决这个问题

**Comment by xianrenjituan** [comment]
token值没复制完整？

**Comment by Musanyu** [comment]
> 

复制完了也是登录失败

**Comment by Musanyu** [comment]
> token值没复制完整？

完整了也登陆不上
浏览器token那里pin-setup我的是false你的图里是true
其他没有不同

**Comment by wuchenjuna** [comment]
对的，复制完全了也是登录不上。
